@startuml
'https://plantuml.com/sequence-diagram

autonumber

title Authentication

actor user
participant gate
participant ipfs as "IPFS"
participant authority
participant NFT

user -> gate: submit(passphrase, file)
gate -> gate: encrypt(passphrase, file)
gate -> ipfs: store encryptedFile
user -> gate: submit(passphrase, encryptedFile)
gate -> gate: generateSingleUsePubKey(passphrase)
gate -> user: send(singleUseUrl)
user -> authority: send(singleUseUrl)
authority -> authority: authenticate(file)
alt ok
authority -> authority:sign(file)
gate <- authority: signature
gate -> gate: encryptWith(passphrase, signature, file, metadata)
gate -> ipfs: store(encryptedFile)
gate -> NFT **: create
gate -> user: return tokenId
end

@enduml
